CREATE TABLE PALAVRAS(
    ID INT PRIMARY KEY,
    NIVEL INT NOT NULL,
    PALAVRA VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE RESULTADOSSOLETRANDO(
    ID INT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL, 
    NUMEROACERTOS INT NOT NULL
);